# Generated by Django 5.0.7 on 2025-03-18 12:17

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_personals', models.IntegerField(verbose_name='Number of Personals')),
                ('satisfaction_percent', models.IntegerField(verbose_name='Satisfaction Percent')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Fullname')),
                ('image', models.ImageField(upload_to='reviews', verbose_name='Reviewer Image')),
                ('comment', tinymce.models.HTMLField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='GiftBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', tinymce.models.HTMLField(verbose_name='Info')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Price')),
                ('stock', models.IntegerField(db_index=True, verbose_name='Stock')),
                ('image', models.ImageField(upload_to='products', verbose_name='Product Image')),
                ('category', models.CharField(choices=[('Mask', 'Mask'), ('Balm', 'Balm'), ('Cream', 'Cream'), ('Oil', 'Oil'), ('Shampoo', 'Shampoo')], db_index=True, max_length=100, verbose_name='Category')),
                ('sales_number', models.IntegerField(db_index=True, verbose_name='Sales Number')),
            ],
            options={
                'indexes': [models.Index(fields=['price'], name='price'), models.Index(fields=['stock'], name='stock'), models.Index(fields=['category'], name='category'), models.Index(fields=['sales_number'], name='sales_number')],
            },
        ),
        migrations.CreateModel(
            name='GiftBoxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('gift_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legerity.giftbox', verbose_name='Gift Box')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='legerity.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legerity.cart', verbose_name='Cart')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='legerity.product', verbose_name='Product')),
            ],
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='user-cart'),
        ),
        migrations.AddIndex(
            model_name='giftbox',
            index=models.Index(fields=['user'], name='user-gift-box'),
        ),
        migrations.AddIndex(
            model_name='giftbox',
            index=models.Index(fields=['user', 'name'], name='user&name'),
        ),
        migrations.AddIndex(
            model_name='giftboxitem',
            index=models.Index(fields=['gift_box'], name='gift_box'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='cart'),
        ),
    ]
