# Generated by Django 5.0.7 on 2025-03-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legerity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales_number',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Sales Number'),
        ),
    ]
