# Generated by Django 5.0.7 on 2025-04-06 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legerity', '0002_alter_product_sales_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='legerity.cart', verbose_name='Cart'),
        ),
    ]
