# Generated by Django 5.0.7 on 2025-05-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legerity', '0004_order_ordergiftbox_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Prepared', 'Prepared'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Prepared', max_length=10),
        ),
    ]
