# Generated by Django 5.0.7 on 2025-05-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legerity', '0007_alter_order_address_alter_order_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftboxitem',
            name='gift_box',
        ),
        migrations.RemoveField(
            model_name='ordergiftbox',
            name='gift_box',
        ),
        migrations.RemoveField(
            model_name='giftboxitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ordergiftbox',
            name='order',
        ),
        migrations.DeleteModel(
            name='GiftBox',
        ),
        migrations.DeleteModel(
            name='GiftBoxItem',
        ),
        migrations.DeleteModel(
            name='OrderGiftBox',
        ),
    ]
