# Generated by Django 5.0.7 on 2025-05-05 03:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legerity', '0008_remove_giftboxitem_gift_box_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^(\\+[0-9]{1,3})?[0-9]{9,15}$')], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Prepared', 'Prepared'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Prepared', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(max_length=50, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='legerity.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='legerity.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='user_index'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phone_number'], name='phone_index'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='status_index'),
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=models.Index(fields=['order'], name='order_index'),
        ),
    ]
